language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: cmake .. -DSC_ENABLE_TESTING=ON && make && make test
branches:
  only:
    - master
    - /^review\/.*$/
notifications:
  irc: "chat.freenode.net#stepcode"
  recipients:
    - scl-dev@groups.google.com
  on_success: change
  on_failure: always
